
\restrict vK3NlS1UJk5w8UgmLgrTj4avT3GsdEHrS44L12IqR1ggAAnjFrr9OV3wxMvR6Wo


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."TTL deleat"() RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$BEGIN
  DELETE FROM public.todos WHERE created_at <= (CURRENT_TIMESTAMP - INTERVAL '1 day');
  RETURN;
END;$$;


ALTER FUNCTION "public"."TTL deleat"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  INSERT INTO public.usels (user_id, username, introduction, place, birth_date, follow)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text, 1, 8)),
    COALESCE('こんにちは、' || (new.raw_user_meta_data->>'displayName') || 'です！', 'よろしくお願いします'),
    '',
    NULL,
    0
  );
  RETURN new;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."search_todos_regex"("p_q" "text" DEFAULT NULL::"text", "p_tag" "text" DEFAULT NULL::"text", "p_limit" integer DEFAULT 50, "p_offset" integer DEFAULT 0) RETURNS TABLE("id" integer, "title" "text", "tags" "text"[], "likes" integer, "user_id" "text", "created_at" timestamp with time zone)
    LANGUAGE "sql" STABLE
    AS $$
  SELECT
    t.id,
    t.title,
    t.tags,
    t.likes,
    t.user_id,
    t.created_at
  FROM public.todos AS t
  WHERE
    (
      COALESCE(p_q, '') = ''
      OR t.title ~* p_q
      OR EXISTS (
        SELECT 1
        FROM unnest(COALESCE(t.tags, ARRAY[]::TEXT[])) AS tg
        WHERE tg ~* p_q
      )
    )
    AND (
      COALESCE(p_tag, '') = ''
      OR EXISTS (
        SELECT 1
        FROM unnest(COALESCE(t.tags, ARRAY[]::TEXT[])) AS tg
        WHERE tg ILIKE '%' || p_tag || '%'
      )
    )
  ORDER BY t.created_at DESC
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 50), 1), 201)
  OFFSET GREATEST(COALESCE(p_offset, 0), 0);
$$;


ALTER FUNCTION "public"."search_todos_regex"("p_q" "text", "p_tag" "text", "p_limit" integer, "p_offset" integer) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."bookmarks" (
    "id" bigint NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "post_id" integer,
    "user_id" "uuid" DEFAULT "gen_random_uuid"(),
    "on" boolean
);


ALTER TABLE "public"."bookmarks" OWNER TO "postgres";


ALTER TABLE "public"."bookmarks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bookmarks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."follows" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "follower_id" "uuid",
    "followed_id" "uuid"
);


ALTER TABLE "public"."follows" OWNER TO "postgres";


ALTER TABLE "public"."follows" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."follows_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."likes" (
    "created_at" timestamp without time zone NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"(),
    "post_id" integer,
    "on" boolean,
    "id" integer NOT NULL
);


ALTER TABLE "public"."likes" OWNER TO "postgres";


ALTER TABLE "public"."likes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."likes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."make_stamp" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "make_stanp_url" "text"
);


ALTER TABLE "public"."make_stamp" OWNER TO "postgres";


ALTER TABLE "public"."make_stamp" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."make_stamp_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."messages" (
    "receiver_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "message" json,
    "username" "text",
    "sender_id" "uuid",
    "text" "text",
    "id" bigint NOT NULL
);


ALTER TABLE "public"."messages" OWNER TO "postgres";


ALTER TABLE "public"."messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notification_settings" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "email_notifications" boolean DEFAULT true,
    "push_notifications" boolean DEFAULT true,
    "mention_notifications" boolean DEFAULT true,
    "like_notifications" boolean DEFAULT true,
    "retweet_notifications" boolean DEFAULT false,
    "follow_notifications" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."notification_settings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."notifications" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "type" character varying(20) NOT NULL,
    "title" "text" NOT NULL,
    "message" "text" NOT NULL,
    "data" "jsonb",
    "read" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."notifications" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."push_subscriptions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "subscription" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."push_subscriptions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."realction" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "mime" "text" DEFAULT 'image/jpeg'::"text" NOT NULL,
    "bytes" "bytea" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."realction" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."replies" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "text" "text",
    "post_id" integer
);


ALTER TABLE "public"."replies" OWNER TO "postgres";


ALTER TABLE "public"."replies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."replies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."stamp" (
    "id" bigint NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "stanp_url" "text",
    "post_id" "text",
    "user_id" "text"
);


ALTER TABLE "public"."stamp" OWNER TO "postgres";


ALTER TABLE "public"."stamp" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."stamp_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."text_" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "text" json
);


ALTER TABLE "public"."text_" OWNER TO "postgres";


ALTER TABLE "public"."text_" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."text__id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tikuribar_chat_messages" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "bar_id" "uuid",
    "user_id" "uuid",
    "username" "text" NOT NULL,
    "message" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."tikuribar_chat_messages" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tikuribar_participants" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "bar_id" "uuid",
    "user_id" "uuid",
    "username" "text" NOT NULL,
    "role" "text" DEFAULT 'listener'::"text",
    "is_muted" boolean DEFAULT false,
    "joined_at" timestamp with time zone DEFAULT "now"(),
    "left_at" timestamp with time zone,
    "is_active" boolean DEFAULT true,
    CONSTRAINT "tikuribar_participants_role_check" CHECK (("role" = ANY (ARRAY['bartender'::"text", 'speaker'::"text", 'listener'::"text"])))
);


ALTER TABLE "public"."tikuribar_participants" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tikuribar_rooms" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "host_user_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "is_active" boolean DEFAULT true,
    "max_participants" integer DEFAULT 50
);


ALTER TABLE "public"."tikuribar_rooms" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tikuribar_voice_messages" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "bar_id" "uuid",
    "user_id" "uuid",
    "username" "text" NOT NULL,
    "audio_url" "text" NOT NULL,
    "duration_ms" integer,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."tikuribar_voice_messages" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."todos" (
    "id" integer NOT NULL,
    "title" "text",
    "end_date" "date",
    "test" smallint,
    "likes" smallint,
    "tags" "text"[],
    "bookmarked" boolean,
    "user_id" "text",
    "created_at" timestamp with time zone,
    "replies" smallint,
    "image_url" "text"
);


ALTER TABLE "public"."todos" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."todos_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."todos_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."todos_id_seq" OWNED BY "public"."todos"."id";



CREATE TABLE IF NOT EXISTS "public"."usels" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "username" "text" DEFAULT 'わしじゃよ'::"text",
    "introduction" "text" DEFAULT 'よろしくお願いします'::"text",
    "place" "text",
    "birth_date" "date",
    "follow" smallint DEFAULT '0'::smallint,
    "site" "text",
    "user_id" "uuid",
    "setID" "text",
    "follower" smallint DEFAULT '0'::smallint,
    "icon_url" "text",
    "has_posted" boolean,
    "isBunkatsu" boolean,
    "banner_url" "text"
);


ALTER TABLE "public"."usels" OWNER TO "postgres";


COMMENT ON COLUMN "public"."usels"."isBunkatsu" IS '分割機能オンオフ';



COMMENT ON COLUMN "public"."usels"."banner_url" IS 'バナーを保存するカラム';



ALTER TABLE "public"."usels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."usels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."users" AS
 SELECT "id",
    "email",
    ("raw_user_meta_data" ->> 'username'::"text") AS "username",
    ("raw_user_meta_data" ->> 'display_name'::"text") AS "display_name"
   FROM "auth"."users";


ALTER VIEW "public"."users" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."weather" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "username" "text",
    "user_avatar" "text",
    "location" "text",
    "weather" "text",
    "temperature" double precision,
    "humidity" double precision,
    "wind_speed" double precision,
    "visibility" double precision,
    "comment" "text",
    "image_url" "text",
    "likes" bigint DEFAULT '0'::bigint NOT NULL,
    "lat" double precision,
    "lng" double precision
);


ALTER TABLE "public"."weather" OWNER TO "postgres";


ALTER TABLE "public"."weather" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."weather_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."todos" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."todos_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."bookmarks"
    ADD CONSTRAINT "bookmarks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."follows"
    ADD CONSTRAINT "follows_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "likes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."make_stamp"
    ADD CONSTRAINT "make_stamp_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notification_settings"
    ADD CONSTRAINT "notification_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notification_settings"
    ADD CONSTRAINT "notification_settings_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."realction"
    ADD CONSTRAINT "realction_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."replies"
    ADD CONSTRAINT "replies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stamp"
    ADD CONSTRAINT "stamp_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."text_"
    ADD CONSTRAINT "text__pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tikuribar_chat_messages"
    ADD CONSTRAINT "tikuribar_chat_messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tikuribar_participants"
    ADD CONSTRAINT "tikuribar_participants_bar_id_user_id_key" UNIQUE ("bar_id", "user_id");



ALTER TABLE ONLY "public"."tikuribar_participants"
    ADD CONSTRAINT "tikuribar_participants_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tikuribar_rooms"
    ADD CONSTRAINT "tikuribar_rooms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tikuribar_voice_messages"
    ADD CONSTRAINT "tikuribar_voice_messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "unique_user_post_like" UNIQUE ("user_id", "post_id");



ALTER TABLE ONLY "public"."usels"
    ADD CONSTRAINT "usels_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."weather"
    ADD CONSTRAINT "weather_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_notification_settings_user_id" ON "public"."notification_settings" USING "btree" ("user_id");



CREATE INDEX "idx_notifications_created_at" ON "public"."notifications" USING "btree" ("created_at" DESC);



CREATE INDEX "idx_notifications_duplicate_prevention" ON "public"."notifications" USING "btree" ("user_id", "type", "created_at") WHERE (("type")::"text" = 'like'::"text");



CREATE INDEX "idx_notifications_user_id" ON "public"."notifications" USING "btree" ("user_id");



CREATE INDEX "idx_push_subscriptions_user_id" ON "public"."push_subscriptions" USING "btree" ("user_id");



ALTER TABLE ONLY "public"."notification_settings"
    ADD CONSTRAINT "notification_settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."realction"
    ADD CONSTRAINT "realction_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tikuribar_chat_messages"
    ADD CONSTRAINT "tikuribar_chat_messages_bar_id_fkey" FOREIGN KEY ("bar_id") REFERENCES "public"."tikuribar_rooms"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tikuribar_chat_messages"
    ADD CONSTRAINT "tikuribar_chat_messages_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tikuribar_participants"
    ADD CONSTRAINT "tikuribar_participants_bar_id_fkey" FOREIGN KEY ("bar_id") REFERENCES "public"."tikuribar_rooms"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tikuribar_participants"
    ADD CONSTRAINT "tikuribar_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tikuribar_rooms"
    ADD CONSTRAINT "tikuribar_rooms_host_user_id_fkey" FOREIGN KEY ("host_user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tikuribar_voice_messages"
    ADD CONSTRAINT "tikuribar_voice_messages_bar_id_fkey" FOREIGN KEY ("bar_id") REFERENCES "public"."tikuribar_rooms"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tikuribar_voice_messages"
    ADD CONSTRAINT "tikuribar_voice_messages_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "24SNS" ON "public"."follows" USING (true) WITH CHECK (true);



CREATE POLICY "Allow all insert" ON "public"."likes" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow all select" ON "public"."bookmarks" FOR SELECT USING (true);



CREATE POLICY "Allow all select" ON "public"."likes" FOR SELECT USING (true);



CREATE POLICY "Allow service_role to insert notifications" ON "public"."notifications" FOR INSERT TO "service_role" WITH CHECK (true);



CREATE POLICY "Allow service_role to read notifications" ON "public"."notifications" FOR SELECT TO "service_role" USING (true);



CREATE POLICY "Anyone can read tikuribar_chat_messages" ON "public"."tikuribar_chat_messages" FOR SELECT USING (true);



CREATE POLICY "Anyone can read tikuribar_participants" ON "public"."tikuribar_participants" FOR SELECT USING (true);



CREATE POLICY "Anyone can read tikuribar_rooms" ON "public"."tikuribar_rooms" FOR SELECT USING (true);



CREATE POLICY "Anyone can read tikuribar_voice_messages" ON "public"."tikuribar_voice_messages" FOR SELECT USING (true);



CREATE POLICY "Authenticated users can create tikuribar_chat_messages" ON "public"."tikuribar_chat_messages" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can create tikuribar_rooms" ON "public"."tikuribar_rooms" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can create tikuribar_voice_messages" ON "public"."tikuribar_voice_messages" FOR INSERT WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Authenticated users can manage tikuribar_participants" ON "public"."tikuribar_participants" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."bookmarks" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."likes" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."todos" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable insert for users based on user_id" ON "public"."usels" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable read access for all users" ON "public"."bookmarks" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."likes" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."usels" FOR SELECT USING (true);



CREATE POLICY "Smart TTL policy" ON "public"."todos" FOR SELECT USING ((("created_at" > (CURRENT_TIMESTAMP - '24:00:00'::interval)) OR ((("auth"."uid"())::"text" = "user_id") AND ("created_at" <= (CURRENT_TIMESTAMP - '24:00:00'::interval)) AND ("created_at" > (CURRENT_TIMESTAMP - '25:00:00'::interval)))));



CREATE POLICY "Users can manage their own notification settings" ON "public"."notification_settings" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own notifications" ON "public"."notifications" TO "authenticated", "anon" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own subscriptions" ON "public"."push_subscriptions" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "all" ON "public"."bookmarks" USING (true) WITH CHECK (true);



CREATE POLICY "all" ON "public"."usels" USING (true) WITH CHECK (true);



ALTER TABLE "public"."bookmarks" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "deleat" ON "public"."likes" FOR DELETE USING (true);



ALTER TABLE "public"."follows" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "insert own" ON "public"."weather" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "insert_own_realction" ON "public"."realction" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."likes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."make_stamp" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "make_stanp_policy" ON "public"."make_stamp" USING (true) WITH CHECK (true);



ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "messagespolicy" ON "public"."messages" USING (true) WITH CHECK (true);



ALTER TABLE "public"."notification_settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."push_subscriptions" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "read all" ON "public"."weather" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."realction" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."replies" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "reply" ON "public"."replies" USING (true) WITH CHECK (true);



CREATE POLICY "select_own_realction" ON "public"."realction" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."stamp" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "stamp_All" ON "public"."stamp" USING (true) WITH CHECK (true);



ALTER TABLE "public"."text_" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tikuribar_chat_messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tikuribar_participants" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tikuribar_rooms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tikuribar_voice_messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."todos" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "update" ON "public"."bookmarks" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "update" ON "public"."likes" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "update" ON "public"."todos" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "update " ON "public"."usels" FOR UPDATE USING (true) WITH CHECK (true);



ALTER TABLE "public"."usels" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."weather" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "ユーザーは自分のuselsデータのみ参照できる" ON "public"."usels" FOR SELECT USING (("user_id" = "auth"."uid"()));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."bookmarks";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."likes";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."text_";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."usels";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."TTL deleat"() TO "anon";
GRANT ALL ON FUNCTION "public"."TTL deleat"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."TTL deleat"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."search_todos_regex"("p_q" "text", "p_tag" "text", "p_limit" integer, "p_offset" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."search_todos_regex"("p_q" "text", "p_tag" "text", "p_limit" integer, "p_offset" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."search_todos_regex"("p_q" "text", "p_tag" "text", "p_limit" integer, "p_offset" integer) TO "service_role";



SET SESSION AUTHORIZATION "postgres";
RESET SESSION AUTHORIZATION;



SET SESSION AUTHORIZATION "postgres";
RESET SESSION AUTHORIZATION;



SET SESSION AUTHORIZATION "postgres";
RESET SESSION AUTHORIZATION;









GRANT ALL ON TABLE "public"."bookmarks" TO "anon";
GRANT ALL ON TABLE "public"."bookmarks" TO "authenticated";
GRANT ALL ON TABLE "public"."bookmarks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bookmarks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bookmarks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bookmarks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."follows" TO "anon";
GRANT ALL ON TABLE "public"."follows" TO "authenticated";
GRANT ALL ON TABLE "public"."follows" TO "service_role";



GRANT ALL ON SEQUENCE "public"."follows_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."follows_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."follows_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."likes" TO "anon";
GRANT ALL ON TABLE "public"."likes" TO "authenticated";
GRANT ALL ON TABLE "public"."likes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."likes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."likes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."likes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."make_stamp" TO "anon";
GRANT ALL ON TABLE "public"."make_stamp" TO "authenticated";
GRANT ALL ON TABLE "public"."make_stamp" TO "service_role";



GRANT ALL ON SEQUENCE "public"."make_stamp_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."make_stamp_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."make_stamp_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."messages" TO "anon";
GRANT ALL ON TABLE "public"."messages" TO "authenticated";
GRANT ALL ON TABLE "public"."messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notification_settings" TO "anon";
GRANT ALL ON TABLE "public"."notification_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."notification_settings" TO "service_role";



GRANT ALL ON TABLE "public"."notifications" TO "anon";
GRANT ALL ON TABLE "public"."notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."notifications" TO "service_role";



GRANT ALL ON TABLE "public"."push_subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "service_role";



GRANT ALL ON TABLE "public"."realction" TO "anon";
GRANT ALL ON TABLE "public"."realction" TO "authenticated";
GRANT ALL ON TABLE "public"."realction" TO "service_role";



GRANT ALL ON TABLE "public"."replies" TO "anon";
GRANT ALL ON TABLE "public"."replies" TO "authenticated";
GRANT ALL ON TABLE "public"."replies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."replies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."replies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."replies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."stamp" TO "anon";
GRANT ALL ON TABLE "public"."stamp" TO "authenticated";
GRANT ALL ON TABLE "public"."stamp" TO "service_role";



GRANT ALL ON SEQUENCE "public"."stamp_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."stamp_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."stamp_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."text_" TO "anon";
GRANT ALL ON TABLE "public"."text_" TO "authenticated";
GRANT ALL ON TABLE "public"."text_" TO "service_role";



GRANT ALL ON SEQUENCE "public"."text__id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."text__id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."text__id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tikuribar_chat_messages" TO "anon";
GRANT ALL ON TABLE "public"."tikuribar_chat_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."tikuribar_chat_messages" TO "service_role";



GRANT ALL ON TABLE "public"."tikuribar_participants" TO "anon";
GRANT ALL ON TABLE "public"."tikuribar_participants" TO "authenticated";
GRANT ALL ON TABLE "public"."tikuribar_participants" TO "service_role";



GRANT ALL ON TABLE "public"."tikuribar_rooms" TO "anon";
GRANT ALL ON TABLE "public"."tikuribar_rooms" TO "authenticated";
GRANT ALL ON TABLE "public"."tikuribar_rooms" TO "service_role";



GRANT ALL ON TABLE "public"."tikuribar_voice_messages" TO "anon";
GRANT ALL ON TABLE "public"."tikuribar_voice_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."tikuribar_voice_messages" TO "service_role";



GRANT ALL ON TABLE "public"."todos" TO "anon";
GRANT ALL ON TABLE "public"."todos" TO "authenticated";
GRANT ALL ON TABLE "public"."todos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."todos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."todos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."todos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."usels" TO "anon";
GRANT ALL ON TABLE "public"."usels" TO "authenticated";
GRANT ALL ON TABLE "public"."usels" TO "service_role";



GRANT ALL ON SEQUENCE "public"."usels_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."usels_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."usels_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON TABLE "public"."weather" TO "anon";
GRANT ALL ON TABLE "public"."weather" TO "authenticated";
GRANT ALL ON TABLE "public"."weather" TO "service_role";



GRANT ALL ON SEQUENCE "public"."weather_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."weather_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."weather_id_seq" TO "service_role";



SET SESSION AUTHORIZATION "postgres";
RESET SESSION AUTHORIZATION;



SET SESSION AUTHORIZATION "postgres";
RESET SESSION AUTHORIZATION;



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























\unrestrict vK3NlS1UJk5w8UgmLgrTj4avT3GsdEHrS44L12IqR1ggAAnjFrr9OV3wxMvR6Wo

RESET ALL;
