


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."TTL deleat"() RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$BEGIN
  DELETE FROM public.todos WHERE created_at <= (CURRENT_TIMESTAMP - INTERVAL '1 day');
  RETURN;
END;$$;


ALTER FUNCTION "public"."TTL deleat"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  INSERT INTO public.usels (user_id, username, introduction, place, birth_date, follow)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text, 1, 8)),
    COALESCE('こんにちは、' || (new.raw_user_meta_data->>'displayName') || 'です！', 'よろしくお願いします'),
    '',
    NULL,
    0
  );
  RETURN new;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."search_todos_pgroonga"("p_q" "text" DEFAULT NULL::"text", "p_tag" "text" DEFAULT NULL::"text", "p_limit" integer DEFAULT 50, "p_offset" integer DEFAULT 0) RETURNS TABLE("id" integer, "title" "text", "tags" "text"[], "likes" integer, "user_id" "text", "created_at" timestamp with time zone)
    LANGUAGE "sql" STABLE
    AS $$
  SELECT
    t.id,
    t.title,
    t.tags,
    t.likes::integer,
    t.user_id,
    t.created_at
  FROM public.todos AS t
  WHERE
    (
      -- p_q が空でない場合、title か tags のどちらかにマッチするか判定
      COALESCE(p_q, '') = ''
      OR t.title &@~ p_q
      OR t.tags &@~ p_q
    )
    AND (
      -- p_tag が指定されている場合、tags 配列内を検索
      COALESCE(p_tag, '') = ''
      OR t.tags &@~ p_tag
    )
  ORDER BY t.created_at DESC
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 50), 1), 201)
  OFFSET GREATEST(COALESCE(p_offset, 0), 0);
$$;


ALTER FUNCTION "public"."search_todos_pgroonga"("p_q" "text", "p_tag" "text", "p_limit" integer, "p_offset" integer) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."sync_todo_likes_count"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.on IS TRUE AND NEW.post_id IS NOT NULL THEN
      UPDATE public.todos
      SET likes = LEAST(COALESCE(likes, 0) + 1, 32767)
      WHERE id = NEW.post_id;
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF COALESCE(OLD.post_id, -1) <> COALESCE(NEW.post_id, -1) THEN
      IF OLD.on IS TRUE AND OLD.post_id IS NOT NULL THEN
        UPDATE public.todos
        SET likes = GREATEST(COALESCE(likes, 0) - 1, 0)
        WHERE id = OLD.post_id;
      END IF;

      IF NEW.on IS TRUE AND NEW.post_id IS NOT NULL THEN
        UPDATE public.todos
        SET likes = LEAST(COALESCE(likes, 0) + 1, 32767)
        WHERE id = NEW.post_id;
      END IF;

      RETURN NEW;
    END IF;

    IF COALESCE(OLD.on, false) = false AND COALESCE(NEW.on, false) = true THEN
      UPDATE public.todos
      SET likes = LEAST(COALESCE(likes, 0) + 1, 32767)
      WHERE id = NEW.post_id;
    ELSIF COALESCE(OLD.on, false) = true AND COALESCE(NEW.on, false) = false THEN
      UPDATE public.todos
      SET likes = GREATEST(COALESCE(likes, 0) - 1, 0)
      WHERE id = NEW.post_id;
    END IF;

    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    IF OLD.on IS TRUE AND OLD.post_id IS NOT NULL THEN
      UPDATE public.todos
      SET likes = GREATEST(COALESCE(likes, 0) - 1, 0)
      WHERE id = OLD.post_id;
    END IF;
    RETURN OLD;
  END IF;

  RETURN NULL;
END;
$$;


ALTER FUNCTION "public"."sync_todo_likes_count"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."bookmarks" (
    "id" bigint NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "post_id" integer,
    "user_id" "uuid" DEFAULT "gen_random_uuid"(),
    "on" boolean
);


ALTER TABLE "public"."bookmarks" OWNER TO "postgres";


ALTER TABLE "public"."bookmarks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bookmarks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."follows" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "follower_id" "uuid",
    "followed_id" "uuid"
);


ALTER TABLE "public"."follows" OWNER TO "postgres";


ALTER TABLE "public"."follows" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."follows_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."infrastructure_logs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "run_id" "uuid" NOT NULL,
    "environment" "text" NOT NULL,
    "source" "text" NOT NULL,
    "log_level" "text" NOT NULL,
    "event_type" "text" NOT NULL,
    "message" "text" NOT NULL,
    "detail" "jsonb",
    "resolved" boolean DEFAULT false,
    CONSTRAINT "infrastructure_logs_environment_check" CHECK (("environment" = ANY (ARRAY['prod'::"text", 'staging'::"text", 'dev'::"text"]))),
    CONSTRAINT "infrastructure_logs_log_level_check" CHECK (("log_level" = ANY (ARRAY['info'::"text", 'warn'::"text", 'error'::"text"]))),
    CONSTRAINT "infrastructure_logs_source_check" CHECK (("source" = ANY (ARRAY['raspberry_pi'::"text", 'supabase'::"text", 'r2'::"text", 'vercel'::"text"])))
);


ALTER TABLE "public"."infrastructure_logs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."likes" (
    "created_at" timestamp without time zone NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"(),
    "post_id" integer,
    "on" boolean,
    "id" integer NOT NULL
);


ALTER TABLE "public"."likes" OWNER TO "postgres";


ALTER TABLE "public"."likes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."likes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."make_stamp" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "make_stanp_url" "text"
);


ALTER TABLE "public"."make_stamp" OWNER TO "postgres";


ALTER TABLE "public"."make_stamp" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."make_stamp_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."messages" (
    "receiver_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "message" json,
    "username" "text",
    "sender_id" "uuid",
    "text" "text",
    "id" bigint NOT NULL
);


ALTER TABLE "public"."messages" OWNER TO "postgres";


ALTER TABLE "public"."messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notification_settings" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "email_notifications" boolean DEFAULT true,
    "push_notifications" boolean DEFAULT true,
    "mention_notifications" boolean DEFAULT true,
    "like_notifications" boolean DEFAULT true,
    "retweet_notifications" boolean DEFAULT false,
    "follow_notifications" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."notification_settings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."notifications" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "type" character varying(20) NOT NULL,
    "title" "text" NOT NULL,
    "message" "text" NOT NULL,
    "data" "jsonb",
    "read" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."notifications" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."push_subscriptions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "subscription" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."push_subscriptions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."realction" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "mime" "text" DEFAULT 'image/jpeg'::"text" NOT NULL,
    "bytes" "bytea" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."realction" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."replies" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "text" "text",
    "post_id" integer
);


ALTER TABLE "public"."replies" OWNER TO "postgres";


ALTER TABLE "public"."replies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."replies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."spot_posts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid",
    "username" "text" NOT NULL,
    "user_icon_url" "text",
    "title" "text" NOT NULL,
    "description" "text" DEFAULT ''::"text",
    "latitude" double precision NOT NULL,
    "longitude" double precision NOT NULL,
    "address" "text" DEFAULT ''::"text",
    "photo_url" "text",
    "category" "text" DEFAULT 'その他'::"text",
    "likes" integer DEFAULT 0,
    "liked_by" "uuid"[] DEFAULT '{}'::"uuid"[],
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."spot_posts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."stamp" (
    "id" bigint NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "stanp_url" "text",
    "post_id" "text",
    "user_id" "text"
);


ALTER TABLE "public"."stamp" OWNER TO "postgres";


ALTER TABLE "public"."stamp" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."stamp_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."text_" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "text" json
);


ALTER TABLE "public"."text_" OWNER TO "postgres";


ALTER TABLE "public"."text_" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."text__id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."todos" (
    "id" integer NOT NULL,
    "title" "text",
    "end_date" "date",
    "test" smallint,
    "likes" smallint,
    "tags" "text"[],
    "bookmarked" boolean,
    "user_id" "text",
    "created_at" timestamp with time zone,
    "replies" smallint,
    "image_url" "text"
);


ALTER TABLE "public"."todos" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."todos_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."todos_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."todos_id_seq" OWNED BY "public"."todos"."id";



CREATE TABLE IF NOT EXISTS "public"."usels" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "username" "text" DEFAULT 'わしじゃよ'::"text",
    "introduction" "text" DEFAULT 'よろしくお願いします'::"text",
    "place" "text",
    "birth_date" "date",
    "follow" smallint DEFAULT '0'::smallint,
    "site" "text",
    "user_id" "uuid",
    "setID" "text",
    "follower" smallint DEFAULT '0'::smallint,
    "icon_url" "text",
    "has_posted" boolean,
    "isBunkatsu" boolean,
    "banner_url" "text"
);


ALTER TABLE "public"."usels" OWNER TO "postgres";


COMMENT ON COLUMN "public"."usels"."isBunkatsu" IS '分割機能オンオフ';



COMMENT ON COLUMN "public"."usels"."banner_url" IS 'バナーを保存するカラム';



ALTER TABLE "public"."usels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."usels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."users" AS
 SELECT "id",
    "email",
    ("raw_user_meta_data" ->> 'username'::"text") AS "username",
    ("raw_user_meta_data" ->> 'display_name'::"text") AS "display_name"
   FROM "auth"."users";


ALTER VIEW "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."todos" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."todos_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."bookmarks"
    ADD CONSTRAINT "bookmarks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."follows"
    ADD CONSTRAINT "follows_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."infrastructure_logs"
    ADD CONSTRAINT "infrastructure_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "likes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."make_stamp"
    ADD CONSTRAINT "make_stamp_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notification_settings"
    ADD CONSTRAINT "notification_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notification_settings"
    ADD CONSTRAINT "notification_settings_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."realction"
    ADD CONSTRAINT "realction_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."replies"
    ADD CONSTRAINT "replies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."spot_posts"
    ADD CONSTRAINT "spot_posts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stamp"
    ADD CONSTRAINT "stamp_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."text_"
    ADD CONSTRAINT "text__pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."likes"
    ADD CONSTRAINT "unique_user_post_like" UNIQUE ("user_id", "post_id");



ALTER TABLE ONLY "public"."usels"
    ADD CONSTRAINT "usels_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_notification_settings_user_id" ON "public"."notification_settings" USING "btree" ("user_id");



CREATE INDEX "idx_notifications_created_at" ON "public"."notifications" USING "btree" ("created_at" DESC);



CREATE INDEX "idx_notifications_duplicate_prevention" ON "public"."notifications" USING "btree" ("user_id", "type", "created_at") WHERE (("type")::"text" = 'like'::"text");



CREATE INDEX "idx_notifications_user_id" ON "public"."notifications" USING "btree" ("user_id");



CREATE INDEX "idx_push_subscriptions_user_id" ON "public"."push_subscriptions" USING "btree" ("user_id");



CREATE INDEX "infrastructure_logs_created_at_idx" ON "public"."infrastructure_logs" USING "btree" ("created_at" DESC);



CREATE INDEX "infrastructure_logs_error_level_idx" ON "public"."infrastructure_logs" USING "btree" ("log_level") WHERE ("log_level" = 'error'::"text");



CREATE INDEX "infrastructure_logs_run_id_idx" ON "public"."infrastructure_logs" USING "btree" ("run_id");



CREATE INDEX "spot_posts_created_at_idx" ON "public"."spot_posts" USING "btree" ("created_at" DESC);



CREATE INDEX "todos_tags_pgroonga_idx" ON "public"."todos" USING "pgroonga" ("tags");



CREATE INDEX "todos_title_pgroonga_idx" ON "public"."todos" USING "pgroonga" ("title");



CREATE OR REPLACE TRIGGER "likes_sync_todo_likes_count" AFTER INSERT OR DELETE OR UPDATE ON "public"."likes" FOR EACH ROW EXECUTE FUNCTION "public"."sync_todo_likes_count"();



ALTER TABLE ONLY "public"."notification_settings"
    ADD CONSTRAINT "notification_settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."realction"
    ADD CONSTRAINT "realction_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."spot_posts"
    ADD CONSTRAINT "spot_posts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE "public"."bookmarks" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "bookmarks_delete_own" ON "public"."bookmarks" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "bookmarks_insert_own" ON "public"."bookmarks" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"() = "user_id") AND ("user_id" IS NOT NULL) AND ("post_id" IS NOT NULL)));



CREATE POLICY "bookmarks_select_own" ON "public"."bookmarks" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "bookmarks_update_own" ON "public"."bookmarks" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."follows" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "follows_delete_own" ON "public"."follows" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "follower_id"));



CREATE POLICY "follows_insert_own" ON "public"."follows" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"() = "follower_id") AND ("follower_id" IS NOT NULL) AND ("followed_id" IS NOT NULL) AND ("follower_id" <> "followed_id")));



CREATE POLICY "follows_select_public" ON "public"."follows" FOR SELECT USING (true);



ALTER TABLE "public"."infrastructure_logs" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "infrastructure_logs_backup_readonly_select" ON "public"."infrastructure_logs" FOR SELECT TO "backup_readonly" USING (true);



CREATE POLICY "infrastructure_logs_service_role_all" ON "public"."infrastructure_logs" TO "service_role" USING (true) WITH CHECK (true);



ALTER TABLE "public"."likes" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "likes_delete_own" ON "public"."likes" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "likes_insert_own" ON "public"."likes" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"() = "user_id") AND ("user_id" IS NOT NULL) AND ("post_id" IS NOT NULL)));



CREATE POLICY "likes_select_public" ON "public"."likes" FOR SELECT USING (true);



CREATE POLICY "likes_update_own" ON "public"."likes" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."make_stamp" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "make_stamp_insert_authenticated" ON "public"."make_stamp" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "make_stamp_select_public" ON "public"."make_stamp" FOR SELECT USING (true);



ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "messages_delete_sender_only" ON "public"."messages" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "sender_id"));



CREATE POLICY "messages_insert_sender_only" ON "public"."messages" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"() = "sender_id") AND ("sender_id" IS NOT NULL) AND ("receiver_id" IS NOT NULL)));



CREATE POLICY "messages_select_participant" ON "public"."messages" FOR SELECT TO "authenticated" USING ((("auth"."uid"() = "sender_id") OR ("auth"."uid"() = "receiver_id")));



ALTER TABLE "public"."notification_settings" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "notification_settings_delete_own" ON "public"."notification_settings" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "notification_settings_insert_own" ON "public"."notification_settings" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "notification_settings_select_own" ON "public"."notification_settings" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "notification_settings_service_role_all" ON "public"."notification_settings" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "notification_settings_update_own" ON "public"."notification_settings" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "notifications_delete_own" ON "public"."notifications" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "notifications_select_own" ON "public"."notifications" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "notifications_service_role_all" ON "public"."notifications" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "notifications_update_own" ON "public"."notifications" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."push_subscriptions" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "push_subscriptions_delete_own" ON "public"."push_subscriptions" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "push_subscriptions_insert_own" ON "public"."push_subscriptions" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "push_subscriptions_select_own" ON "public"."push_subscriptions" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "push_subscriptions_service_role_all" ON "public"."push_subscriptions" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "push_subscriptions_update_own" ON "public"."push_subscriptions" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."realction" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "realction_delete_own" ON "public"."realction" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "realction_insert_own" ON "public"."realction" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "realction_select_own" ON "public"."realction" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "realction_update_own" ON "public"."realction" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."replies" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "replies_delete_own" ON "public"."replies" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "replies_insert_own" ON "public"."replies" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "replies_select_public" ON "public"."replies" FOR SELECT USING (true);



ALTER TABLE "public"."spot_posts" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "spot_posts_delete_own" ON "public"."spot_posts" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "spot_posts_insert_own" ON "public"."spot_posts" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "spot_posts_select_public" ON "public"."spot_posts" FOR SELECT USING (true);



CREATE POLICY "spot_posts_update_own" ON "public"."spot_posts" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."stamp" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "stamp_delete_own" ON "public"."stamp" FOR DELETE TO "authenticated" USING ((("auth"."uid"())::"text" = "user_id"));



CREATE POLICY "stamp_insert_own" ON "public"."stamp" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"())::"text" = "user_id"));



CREATE POLICY "stamp_select_public" ON "public"."stamp" FOR SELECT USING (true);



ALTER TABLE "public"."text_" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."todos" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "todos_delete_own" ON "public"."todos" FOR DELETE TO "authenticated" USING ((("auth"."uid"())::"text" = "user_id"));



CREATE POLICY "todos_insert_own" ON "public"."todos" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"())::"text" = "user_id"));



CREATE POLICY "todos_select_public" ON "public"."todos" FOR SELECT USING (true);



CREATE POLICY "todos_update_own" ON "public"."todos" FOR UPDATE TO "authenticated" USING ((("auth"."uid"())::"text" = "user_id")) WITH CHECK ((("auth"."uid"())::"text" = "user_id"));



ALTER TABLE "public"."usels" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "usels_delete_own" ON "public"."usels" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "usels_insert_own" ON "public"."usels" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "usels_select_public" ON "public"."usels" FOR SELECT USING (true);



CREATE POLICY "usels_update_own" ON "public"."usels" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT USAGE ON SCHEMA "public" TO "backup_readonly";
GRANT USAGE ON SCHEMA "public" TO "backup_cleanup";



GRANT ALL ON FUNCTION "public"."TTL deleat"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."search_todos_pgroonga"("p_q" "text", "p_tag" "text", "p_limit" integer, "p_offset" integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."sync_todo_likes_count"() TO "service_role";



GRANT ALL ON TABLE "public"."bookmarks" TO "service_role";
GRANT SELECT ON TABLE "public"."bookmarks" TO "backup_readonly";



GRANT ALL ON SEQUENCE "public"."bookmarks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."follows" TO "service_role";
GRANT SELECT ON TABLE "public"."follows" TO "backup_readonly";



GRANT ALL ON SEQUENCE "public"."follows_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."infrastructure_logs" TO "service_role";
GRANT SELECT ON TABLE "public"."infrastructure_logs" TO "backup_readonly";



GRANT ALL ON TABLE "public"."likes" TO "service_role";
GRANT SELECT ON TABLE "public"."likes" TO "backup_readonly";



GRANT ALL ON SEQUENCE "public"."likes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."make_stamp" TO "service_role";
GRANT SELECT ON TABLE "public"."make_stamp" TO "backup_readonly";



GRANT ALL ON SEQUENCE "public"."make_stamp_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."messages" TO "service_role";
GRANT SELECT ON TABLE "public"."messages" TO "backup_readonly";



GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notification_settings" TO "service_role";
GRANT SELECT ON TABLE "public"."notification_settings" TO "backup_readonly";



GRANT ALL ON TABLE "public"."notifications" TO "service_role";
GRANT SELECT ON TABLE "public"."notifications" TO "backup_readonly";



GRANT ALL ON TABLE "public"."push_subscriptions" TO "service_role";
GRANT SELECT ON TABLE "public"."push_subscriptions" TO "backup_readonly";



GRANT ALL ON TABLE "public"."realction" TO "service_role";
GRANT SELECT ON TABLE "public"."realction" TO "backup_readonly";



GRANT ALL ON TABLE "public"."replies" TO "service_role";
GRANT SELECT ON TABLE "public"."replies" TO "backup_readonly";
GRANT SELECT,DELETE ON TABLE "public"."replies" TO "backup_cleanup";



GRANT ALL ON SEQUENCE "public"."replies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."spot_posts" TO "service_role";
GRANT SELECT ON TABLE "public"."spot_posts" TO "backup_readonly";



GRANT ALL ON TABLE "public"."stamp" TO "service_role";
GRANT SELECT ON TABLE "public"."stamp" TO "backup_readonly";



GRANT ALL ON SEQUENCE "public"."stamp_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."text_" TO "service_role";
GRANT SELECT ON TABLE "public"."text_" TO "backup_readonly";



GRANT ALL ON SEQUENCE "public"."text__id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."todos" TO "service_role";
GRANT SELECT ON TABLE "public"."todos" TO "backup_readonly";
GRANT SELECT,DELETE ON TABLE "public"."todos" TO "backup_cleanup";



GRANT ALL ON SEQUENCE "public"."todos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."usels" TO "service_role";
GRANT SELECT ON TABLE "public"."usels" TO "backup_readonly";



GRANT ALL ON SEQUENCE "public"."usels_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "service_role";
GRANT SELECT ON TABLE "public"."users" TO "backup_readonly";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT ON TABLES TO "backup_readonly";







