-- ============================================================
-- Jyogi SNS - Supabase 用セットアップ SQL
-- このファイルを Supabase Dashboard の SQL Editor に貼り付けて実行してください
-- ============================================================


-- ============================================================
-- Step 1: Extensions
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgroonga;
CREATE EXTENSION IF NOT EXISTS vector;


-- ============================================================
-- Step 2: Tables
-- ============================================================

-- ブックマーク
CREATE TABLE IF NOT EXISTS public.bookmarks (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  post_id    integer,
  user_id    uuid,
  "on"       boolean
);

-- フォロー関係
CREATE TABLE IF NOT EXISTS public.follows (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamp with time zone NOT NULL DEFAULT now(),
  follower_id uuid,
  followed_id uuid
);

-- いいね
CREATE TABLE IF NOT EXISTS public.likes (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  user_id    uuid,
  post_id    integer,
  "on"       boolean,
  CONSTRAINT unique_user_post_like UNIQUE (user_id, post_id)
);

-- ユーザー作成スタンプ（永続化。24時間TTLは設けない）
CREATE TABLE IF NOT EXISTS public.make_stamp (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     timestamp with time zone NOT NULL DEFAULT now(),
  make_stanp_url text
);

-- ダイレクトメッセージ
CREATE TABLE IF NOT EXISTS public.messages (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamp with time zone DEFAULT now(),
  receiver_id uuid,
  sender_id   uuid,
  message     json,
  username    text,
  text        text
);

-- 通知設定
CREATE TABLE IF NOT EXISTS public.notification_settings (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  email_notifications   boolean DEFAULT true,
  push_notifications    boolean DEFAULT true,
  mention_notifications boolean DEFAULT true,
  like_notifications    boolean DEFAULT true,
  retweet_notifications boolean DEFAULT false,
  follow_notifications  boolean DEFAULT true,
  created_at            timestamp with time zone DEFAULT now(),
  updated_at            timestamp with time zone DEFAULT now()
);

-- 通知
CREATE TABLE IF NOT EXISTS public.notifications (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type       character varying(20) NOT NULL,
  title      text NOT NULL,
  message    text NOT NULL,
  data       jsonb,
  read       boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

-- Webプッシュ購読情報
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subscription jsonb NOT NULL,
  created_at   timestamp with time zone DEFAULT now(),
  updated_at   timestamp with time zone DEFAULT now()
);

-- REALctionバイナリ画像（/realction, /gallery で使用）
CREATE TABLE IF NOT EXISTS public.realction (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  mime       text NOT NULL DEFAULT 'image/jpeg',
  bytes      bytea NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- リプライ
CREATE TABLE IF NOT EXISTS public.replies (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id    uuid,
  text       text,
  post_id    integer
);

-- スポット投稿（/map で使用）
CREATE TABLE IF NOT EXISTS public.spot_posts (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid REFERENCES auth.users(id),
  username     text NOT NULL,
  user_icon_url text,
  title        text NOT NULL,
  description  text DEFAULT '',
  latitude     double precision NOT NULL,
  longitude    double precision NOT NULL,
  address      text DEFAULT '',
  photo_url    text,
  category     text DEFAULT 'その他',
  likes        integer DEFAULT 0,
  liked_by     uuid[] DEFAULT '{}',
  created_at   timestamp with time zone DEFAULT now()
);

-- スタンプリアクション（user_id は text のまま）
CREATE TABLE IF NOT EXISTS public.stamp (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  stanp_url  text,
  post_id    text,
  user_id    text
);

-- 投稿（コアテーブル）
-- user_id: text → uuid に変更済み
CREATE TABLE IF NOT EXISTS public.todos (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      text,
  likes      smallint,
  tags       text[],
  user_id    uuid,
  created_at timestamp with time zone,
  replies    smallint,
  image_url  text
);

-- ユーザープロフィール
-- displayName カラム追加・user_id UNIQUE
CREATE TABLE IF NOT EXISTS public.usels (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   timestamp with time zone NOT NULL DEFAULT now(),
  username     text DEFAULT 'わしじゃよ',
  "displayName" text,
  introduction text DEFAULT 'よろしくお願いします',
  place        text,
  birth_date   date,
  follow       smallint DEFAULT 0,
  site         text,
  user_id      uuid UNIQUE,
  "setID"      text,
  follower     smallint DEFAULT 0,
  icon_url     text,
  has_posted   boolean,
  "isBunkatsu" boolean,
  banner_url   text
);

COMMENT ON COLUMN public.usels."isBunkatsu" IS '分割機能オンオフ';
COMMENT ON COLUMN public.usels.banner_url IS 'バナーを保存するカラム';
COMMENT ON COLUMN public.usels."displayName" IS '表示名（auth.users の raw_user_meta_data->displayName と同期）';


-- auth.users の VIEW
CREATE OR REPLACE VIEW public.users AS
  SELECT
    id,
    email,
    (raw_user_meta_data ->> 'username') AS username,
    (raw_user_meta_data ->> 'display_name') AS display_name
  FROM auth.users;


-- ============================================================
-- Step 3: Functions
-- ============================================================

-- 新規ユーザー登録時に usels テーブルへプロフィールを自動作成
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.usels (user_id, username, "displayName", introduction, place, birth_date, follow)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text, 1, 8)),
    COALESCE(
      new.raw_user_meta_data->>'displayName',
      new.raw_user_meta_data->>'username',
      'ユーザー'
    ),
    'よろしくお願いします',
    '',
    NULL,
    0
  )
  ON CONFLICT (user_id) DO NOTHING;
  RETURN new;
END;
$$;


-- likes 変更時に todos.likes カウンタを同期
CREATE OR REPLACE FUNCTION public.sync_todo_likes_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.on IS TRUE AND NEW.post_id IS NOT NULL THEN
      UPDATE public.todos
        SET likes = LEAST(COALESCE(likes, 0) + 1, 32767)
        WHERE id = NEW.post_id;
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF COALESCE(OLD.post_id, -1) <> COALESCE(NEW.post_id, -1) THEN
      IF OLD.on IS TRUE AND OLD.post_id IS NOT NULL THEN
        UPDATE public.todos SET likes = GREATEST(COALESCE(likes, 0) - 1, 0) WHERE id = OLD.post_id;
      END IF;
      IF NEW.on IS TRUE AND NEW.post_id IS NOT NULL THEN
        UPDATE public.todos SET likes = LEAST(COALESCE(likes, 0) + 1, 32767) WHERE id = NEW.post_id;
      END IF;
      RETURN NEW;
    END IF;

    IF COALESCE(OLD.on, false) = false AND COALESCE(NEW.on, false) = true THEN
      UPDATE public.todos SET likes = LEAST(COALESCE(likes, 0) + 1, 32767) WHERE id = NEW.post_id;
    ELSIF COALESCE(OLD.on, false) = true AND COALESCE(NEW.on, false) = false THEN
      UPDATE public.todos SET likes = GREATEST(COALESCE(likes, 0) - 1, 0) WHERE id = OLD.post_id;
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    IF OLD.on IS TRUE AND OLD.post_id IS NOT NULL THEN
      UPDATE public.todos SET likes = GREATEST(COALESCE(likes, 0) - 1, 0) WHERE id = OLD.post_id;
    END IF;
    RETURN OLD;
  END IF;

  RETURN NULL;
END;
$$;


-- todos 全文検索 RPC（pgroonga）
CREATE OR REPLACE FUNCTION public.search_todos_pgroonga(
  p_q    text    DEFAULT NULL,
  p_tag  text    DEFAULT NULL,
  p_limit  integer DEFAULT 50,
  p_offset integer DEFAULT 0
)
RETURNS TABLE(
  id         integer,
  title      text,
  tags       text[],
  likes      integer,
  user_id    text,
  created_at timestamp with time zone
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    t.id,
    t.title,
    t.tags,
    t.likes::integer,
    t.user_id::text,
    t.created_at
  FROM public.todos AS t
  WHERE
    (COALESCE(p_q, '') = '' OR t.title &@~ p_q OR t.tags &@~ p_q)
    AND (COALESCE(p_tag, '') = '' OR t.tags &@~ p_tag)
  ORDER BY t.created_at DESC
  LIMIT  LEAST(GREATEST(COALESCE(p_limit, 50), 1), 201)
  OFFSET GREATEST(COALESCE(p_offset, 0), 0);
$$;


-- ============================================================
-- Step 4: Indexes
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_notification_settings_user_id ON public.notification_settings USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_duplicate_prevention ON public.notifications USING btree (user_id, type, created_at) WHERE ((type)::text = 'like'::text);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_id ON public.push_subscriptions USING btree (user_id);
CREATE INDEX IF NOT EXISTS spot_posts_created_at_idx ON public.spot_posts USING btree (created_at DESC);

-- pgroonga インデックス（日本語全文検索）
CREATE INDEX IF NOT EXISTS todos_tags_pgroonga_idx ON public.todos USING pgroonga (tags);
CREATE INDEX IF NOT EXISTS todos_title_pgroonga_idx ON public.todos USING pgroonga (title);

-- パフォーマンス用インデックス
CREATE INDEX IF NOT EXISTS todos_user_id_idx ON public.todos USING btree (user_id);
CREATE INDEX IF NOT EXISTS todos_created_at_idx ON public.todos USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS replies_post_id_idx ON public.replies USING btree (post_id);
CREATE INDEX IF NOT EXISTS messages_sender_receiver_idx ON public.messages USING btree (sender_id, receiver_id);
CREATE INDEX IF NOT EXISTS messages_created_at_idx ON public.messages USING btree (created_at ASC);
CREATE INDEX IF NOT EXISTS make_stamp_created_at_idx ON public.make_stamp USING btree (created_at DESC);


-- ============================================================
-- Step 5: Triggers
-- ============================================================

-- likes 変更時に todos.likes を同期
CREATE OR REPLACE TRIGGER likes_sync_todo_likes_count
  AFTER INSERT OR DELETE OR UPDATE ON public.likes
  FOR EACH ROW EXECUTE FUNCTION public.sync_todo_likes_count();

-- 新規ユーザー登録時に usels へプロフィールを自動作成
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- Step 6: Row Level Security (RLS)
-- ============================================================

-- bookmarks
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;
CREATE POLICY bookmarks_select_own ON public.bookmarks FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY bookmarks_insert_own ON public.bookmarks FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id AND user_id IS NOT NULL AND post_id IS NOT NULL);
CREATE POLICY bookmarks_update_own ON public.bookmarks FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY bookmarks_delete_own ON public.bookmarks FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- follows
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
CREATE POLICY follows_select_public ON public.follows FOR SELECT USING (true);
CREATE POLICY follows_insert_own ON public.follows FOR INSERT TO authenticated WITH CHECK (auth.uid() = follower_id AND follower_id IS NOT NULL AND followed_id IS NOT NULL AND follower_id <> followed_id);
CREATE POLICY follows_delete_own ON public.follows FOR DELETE TO authenticated USING (auth.uid() = follower_id);

-- likes
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY likes_select_public ON public.likes FOR SELECT USING (true);
CREATE POLICY likes_insert_own ON public.likes FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id AND user_id IS NOT NULL AND post_id IS NOT NULL);
CREATE POLICY likes_update_own ON public.likes FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY likes_delete_own ON public.likes FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- make_stamp
ALTER TABLE public.make_stamp ENABLE ROW LEVEL SECURITY;
CREATE POLICY make_stamp_select_public ON public.make_stamp FOR SELECT USING (true);
CREATE POLICY make_stamp_insert_authenticated ON public.make_stamp FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

-- messages
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY messages_select_participant ON public.messages FOR SELECT TO authenticated USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
CREATE POLICY messages_insert_sender_only ON public.messages FOR INSERT TO authenticated WITH CHECK (auth.uid() = sender_id AND sender_id IS NOT NULL AND receiver_id IS NOT NULL);
CREATE POLICY messages_delete_sender_only ON public.messages FOR DELETE TO authenticated USING (auth.uid() = sender_id);

-- notification_settings
ALTER TABLE public.notification_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY notification_settings_select_own ON public.notification_settings FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY notification_settings_insert_own ON public.notification_settings FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY notification_settings_update_own ON public.notification_settings FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY notification_settings_delete_own ON public.notification_settings FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY notification_settings_service_role_all ON public.notification_settings TO service_role USING (true) WITH CHECK (true);

-- notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY notifications_select_own ON public.notifications FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY notifications_update_own ON public.notifications FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY notifications_delete_own ON public.notifications FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY notifications_service_role_all ON public.notifications TO service_role USING (true) WITH CHECK (true);

-- push_subscriptions
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY push_subscriptions_select_own ON public.push_subscriptions FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY push_subscriptions_insert_own ON public.push_subscriptions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY push_subscriptions_update_own ON public.push_subscriptions FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY push_subscriptions_delete_own ON public.push_subscriptions FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY push_subscriptions_service_role_all ON public.push_subscriptions TO service_role USING (true) WITH CHECK (true);

-- realction
ALTER TABLE public.realction ENABLE ROW LEVEL SECURITY;
CREATE POLICY realction_select_own ON public.realction FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY realction_insert_own ON public.realction FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY realction_update_own ON public.realction FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY realction_delete_own ON public.realction FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- replies
ALTER TABLE public.replies ENABLE ROW LEVEL SECURITY;
CREATE POLICY replies_select_public ON public.replies FOR SELECT USING (true);
CREATE POLICY replies_insert_own ON public.replies FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY replies_delete_own ON public.replies FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- spot_posts
ALTER TABLE public.spot_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY spot_posts_select_public ON public.spot_posts FOR SELECT USING (true);
CREATE POLICY spot_posts_insert_own ON public.spot_posts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY spot_posts_update_own ON public.spot_posts FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY spot_posts_delete_own ON public.spot_posts FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- stamp（user_id が text 型なので ::text キャスト必要）
ALTER TABLE public.stamp ENABLE ROW LEVEL SECURITY;
CREATE POLICY stamp_select_public ON public.stamp FOR SELECT USING (true);
CREATE POLICY stamp_insert_own ON public.stamp FOR INSERT TO authenticated WITH CHECK ((auth.uid())::text = user_id);
CREATE POLICY stamp_delete_own ON public.stamp FOR DELETE TO authenticated USING ((auth.uid())::text = user_id);

-- todos（user_id が uuid 型になったのでキャスト不要）
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
CREATE POLICY todos_select_public ON public.todos FOR SELECT USING (true);
CREATE POLICY todos_insert_own ON public.todos FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY todos_update_own ON public.todos FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY todos_delete_own ON public.todos FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- usels
ALTER TABLE public.usels ENABLE ROW LEVEL SECURITY;
CREATE POLICY usels_select_public ON public.usels FOR SELECT USING (true);
CREATE POLICY usels_insert_own ON public.usels FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY usels_update_own ON public.usels FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY usels_delete_own ON public.usels FOR DELETE TO authenticated USING (auth.uid() = user_id);


-- ============================================================
-- Step 7: Realtime パブリケーション設定
-- ============================================================

ALTER PUBLICATION supabase_realtime ADD TABLE public.todos;
ALTER PUBLICATION supabase_realtime ADD TABLE public.replies;
ALTER PUBLICATION supabase_realtime ADD TABLE public.likes;
ALTER PUBLICATION supabase_realtime ADD TABLE public.stamp;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.spot_posts;
